@hostName = http://localhost:5194
#@hostName = https://localhost:7240

###
GET {{hostName}}/weatherforecast?api-version=2023-11-20

###
GET {{hostName}}/weatherforecast?api-version=2023-11-22

###
GET {{hostName}}/weatherSummaries/2?api-version=2023-11-22 